"use client";

import { FormEvent, useMemo, useState, useTransition } from "react";
import { ArrowUpRight, CircleDollarSign, Landmark, PiggyBank, Plus, ReceiptText, RefreshCw, Sparkles, TrendingDown, WalletCards } from "lucide-react";
import { addMoneyExpenseAction, addMoneyIncomeAction, addRecurringExpenseAction, addSavingsDepositAction, addSavingsPlanAction, setPocketMoneyAction } from "@/app/(app)/actions";
import { formatMoney } from "@/lib/money";
import { useToast } from "@/components/ToastProvider";

type Category = { id: string; name: string; color: string };
type Expense = { id: string; description: string; amountMinor: number; kind: "EXPENSE" | "INCOME"; spentOn: string; categoryId: string | null; category: { name: string; color: string } | null };
type Budget = { id: string; name: string; limitMinor: number; savedMinor: number; categoryId: string | null; category: { name: string; color: string } | null };
type Recurring = { id: string; description: string; amountMinor: number; intervalDays: number; category: { name: string; color: string } | null };

const money = (amount: number, currency: string) => formatMoney(amount, currency, currency === "INR" ? "en-IN" : "en-US");

export function MoneyWorkspace({ categories, expenses, budgets, recurring }: { currency: string; categories: Category[]; expenses: Expense[]; budgets: Budget[]; recurring: Recurring[] }) {
  const currency = "INR";
  const { toast } = useToast();
  const [expenseOpen, setExpenseOpen] = useState(false);
  const [pocketOpen, setPocketOpen] = useState(false);
  const [savingOpen, setSavingOpen] = useState(false);
  const [incomeOpen, setIncomeOpen] = useState(false);
  const [recurringOpen, setRecurringOpen] = useState(false);
  const [depositOpen, setDepositOpen] = useState(false);
  const [pending, startTransition] = useTransition();
  const totals = useMemo(() => {
    const now = new Date();
    const daysLeft = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate() - now.getDate() + 1;
    const income = expenses.filter((entry) => entry.kind === "INCOME").reduce((sum, entry) => sum + entry.amountMinor, 0);
    const spent = expenses.filter((entry) => entry.kind === "EXPENSE").reduce((sum, entry) => sum + entry.amountMinor, 0);
    const savingPlans = budgets.filter((budget) => !budget.categoryId && budget.name.startsWith("Save ·"));
    const savingsTarget = savingPlans.reduce((sum, budget) => sum + budget.limitMinor, 0);
    const saved = savingPlans.reduce((sum, budget) => sum + budget.savedMinor, 0);
    const savingsRemaining = Math.max(0, savingsTarget - saved);
    const recurringDaily = recurring.reduce((sum, plan) => sum + Math.ceil(plan.amountMinor / plan.intervalDays), 0);
    const recurringRemainder = recurringDaily * daysLeft;
    const cashLeft = income - spent;
    // A savings target is a protected amount, not a transaction. The cash
    // balance remains truthful; only *safe-to-spend* reserves what is still
    // needed after money already placed in savings.
    const reserveForSavings = savingsRemaining;
    const safePool = cashLeft - recurringRemainder - reserveForSavings;
    const savePerDay = Math.max(0, Math.ceil(reserveForSavings / Math.max(1, daysLeft)));
    return { income, spent, savingsTarget, saved, savingsRemaining, cashLeft, daysLeft, recurringDaily, recurringRemainder, reserveForSavings, savePerDay, safe: Math.max(0, Math.floor(safePool / Math.max(1, daysLeft))) };
  }, [budgets, expenses, recurring]);
  const categorySpend = useMemo(() => categories.map((category) => ({ ...category, spent: expenses.filter((entry) => entry.kind === "EXPENSE" && entry.categoryId === category.id).reduce((sum, entry) => sum + entry.amountMinor, 0), budget: budgets.find((budget) => budget.categoryId === category.id)?.limitMinor ?? 0 })).filter((category) => category.spent || category.budget), [budgets, categories, expenses]);
  const chart = useMemo(() => Array.from({ length: 7 }, (_, index) => {
    const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index));
    const key = date.toISOString().slice(0, 10);
    return { label: new Intl.DateTimeFormat("en-US", { weekday: "narrow" }).format(date), value: expenses.filter((entry) => entry.kind === "EXPENSE" && entry.spentOn.slice(0, 10) === key).reduce((sum, entry) => sum + entry.amountMinor, 0) };
  }), [expenses]);
  const maxBar = Math.max(...chart.map((point) => point.value), 1);
  const recent = expenses.filter((entry) => entry.kind === "EXPENSE").slice(0, 5);

  const submitExpense = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    startTransition(async () => { const result = await addMoneyExpenseAction({ amount: Number(form.get("amount")), description: String(form.get("description")), categoryId: String(form.get("category") || "") || null }); if (result.error) return toast(result.error, "error"); toast("Expense added."); setExpenseOpen(false); });
  };
  const submitIncome = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { const result = await addMoneyIncomeAction({ amount: Number(form.get("amount")), description: String(form.get("description")) }); if (result.error) return toast(result.error, "error"); toast("Money received added."); setIncomeOpen(false); }); };
  const submitRecurring = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { const result = await addRecurringExpenseAction({ amount: Number(form.get("amount")), description: String(form.get("description")), categoryId: String(form.get("category") || "") || null, intervalDays: Number(form.get("frequency")) }); if (result.error) return toast(result.error, "error"); toast("Recurring plan added."); setRecurringOpen(false); }); };
  const submitPocket = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { const result = await setPocketMoneyAction(Number(form.get("amount"))); if (result.error) return toast(result.error, "error"); toast("Pocket money updated."); setPocketOpen(false); }); };
  const submitSaving = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { const result = await addSavingsPlanAction({ name: String(form.get("name")), target: Number(form.get("target")) }); if (result.error) return toast(result.error, "error"); toast("Savings plan added."); setSavingOpen(false); }); };
  const submitDeposit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { const result = await addSavingsDepositAction({ budgetId: String(form.get("plan")), amount: Number(form.get("amount")) }); if (result.error) return toast(result.error, "error"); toast("Savings updated."); setDepositOpen(false); }); };

  return <div className="money-page">
    <header className="money-heading"><div><p>Money · ₹</p><h1>Your month, <em>under control.</em></h1><span>Plan pocket money, day-to-day costs, and what you want to save.</span></div><div className="money-head-actions"><button className="money-plain-action" onClick={() => setIncomeOpen(true)}><Plus size={15} /> Add money</button><button onClick={() => setExpenseOpen(true)}><Plus size={16} /> Add expense</button></div></header>
    <section className="money-runway"><div className="money-runway-copy"><span><WalletCards size={16} /> Cash left this month</span><b>{money(totals.cashLeft, currency)}</b><p>what you have received, minus actual expenses</p><div><button onClick={() => setPocketOpen(true)}>{totals.income ? "Edit pocket money" : "Set pocket money"}</button><small>{totals.daysLeft} days left this month</small></div></div><div className="money-safe"><Sparkles size={17} /><span>Safe to spend today</span><b>{money(totals.safe, currency)}</b><small>after recurring costs and your savings target</small></div><div className="money-runway-stats"><div><TrendingDown size={16} /><span>Spent</span><b>{money(totals.spent, currency)}</b></div><div><PiggyBank size={16} /><span>Savings target</span><b>{money(totals.savingsTarget, currency)}</b></div></div></section>
    <section className="money-save-first"><div><PiggyBank size={21} /><div><span>Save first</span><h2>Put aside {money(totals.savePerDay, currency)} a day to reach your goal.</h2><p>{totals.savingsTarget ? `${money(totals.saved, currency)} saved of ${money(totals.savingsTarget, currency)}. LifeOS protects the remaining ${money(totals.savingsRemaining, currency)} before suggesting what you can spend.` : "Set a savings target and LifeOS will work out the daily amount for you."}</p></div></div><div><small>Recurring basics</small><b>{money(totals.recurringDaily, currency)} / day</b><button onClick={() => setRecurringOpen(true)}><RefreshCw size={13} /> Plan recurring</button></div></section>
    <div className="money-grid"><section className="money-card money-chart-card"><header><div><span>Last 7 days</span><h2>Where your money went</h2></div><b>{money(totals.spent, currency)} <small>this month</small></b></header><div className="money-bars">{chart.map((point, index) => <div key={`${point.label}-${index}`}><i style={{ height: `${Math.max(point.value ? 12 : 3, Math.round((point.value / maxBar) * 100))}%` }} title={money(point.value, currency)} /><small>{point.label}</small></div>)}</div><p>This graph shows your actual daily spending—not a made-up score.</p></section>
      <section className="money-card money-plan-card"><header><div><span>Plan expenses</span><h2>Category budgets</h2></div><button onClick={() => setExpenseOpen(true)}><Plus size={14} /></button></header>{categorySpend.length ? <div className="money-budget-list">{categorySpend.map((category) => { const percent = category.budget ? Math.min(100, Math.round((category.spent / category.budget) * 100)) : 0; return <div key={category.id}><div><i style={{ background: category.color }} /><b>{category.name}</b><small>{money(category.spent, currency)}{category.budget ? ` / ${money(category.budget, currency)}` : " spent"}</small></div>{category.budget ? <span><i style={{ width: `${percent}%`, background: category.color }} /></span> : <em>Set a budget from planning</em>}</div>; })}</div> : <p className="money-empty">Add expenses to see where your month is going.</p>}</section>
      <section className="money-card money-save-card"><header><div><span>Save</span><h2>Plans worth keeping</h2></div><div className="money-card-actions"><button onClick={() => setDepositOpen(true)}>Add saved</button><button onClick={() => setSavingOpen(true)}><Plus size={14} /> New plan</button></div></header>{budgets.filter((budget) => !budget.categoryId && budget.name.startsWith("Save ·")).length ? <div className="money-savings">{budgets.filter((budget) => !budget.categoryId && budget.name.startsWith("Save ·")).map((budget) => { const percent = Math.min(100, Math.round((budget.savedMinor / budget.limitMinor) * 100)); return <div key={budget.id}><PiggyBank size={17} /><div><b>{budget.name.replace("Save · ", "")}</b><small>{money(budget.savedMinor, currency)} saved of {money(budget.limitMinor, currency)}</small><i><i style={{ width: `${percent}%` }} /></i></div><span>{percent}%</span></div>; })}</div> : <div className="money-save-empty"><Landmark size={23} /><p>Give your extra money a job.</p><button onClick={() => setSavingOpen(true)}>Start a savings plan <ArrowUpRight size={14} /></button></div>}</section>
      <section className="money-card money-recurring"><header><div><span>Everyday basics</span><h2>Recurring plans</h2></div><button onClick={() => setRecurringOpen(true)}><Plus size={14} /> Add</button></header>{recurring.length ? <div className="money-recurring-list">{recurring.map((plan) => <div key={plan.id}><span style={{ background: plan.category?.color ?? "#df8aa7" }}><RefreshCw size={13} /></span><div><b>{plan.description}</b><small>{plan.intervalDays === 1 ? "Every day" : "Every week"}{plan.category ? ` · ${plan.category.name}` : ""}</small></div><strong>{money(plan.amountMinor, currency)}</strong></div>)}</div> : <div className="money-save-empty"><ReceiptText size={23} /><p>Plan daily costs like rickshaw or food once.</p><button onClick={() => setRecurringOpen(true)}>Add a recurring expense <ArrowUpRight size={14} /></button></div>}</section>
      <section className="money-card money-recent"><header><div><span>Recent</span><h2>Latest expenses</h2></div></header>{recent.length ? <div>{recent.map((entry) => <article key={entry.id}><span style={{ background: entry.category?.color ?? "#df8aa7" }}><ReceiptText size={14} /></span><div><b>{entry.description}</b><small>{entry.category?.name ?? "Uncategorised"}</small></div><strong>−{money(entry.amountMinor, currency)}</strong></article>)}</div> : <p className="money-empty">Your recent expenses will show here.</p>}</section></div>
    {expenseOpen && <MoneyDialog title="Add expense" onClose={() => setExpenseOpen(false)}><form onSubmit={submitExpense}><label>What did you spend on?<input name="description" placeholder="e.g. Canteen lunch" autoFocus required /></label><label>Amount<input name="amount" type="number" min="1" step="0.01" placeholder="0" required /></label><label>Category<select name="category" defaultValue=""><option value="">Choose a category</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><button disabled={pending}>Save expense</button></form></MoneyDialog>}
    {pocketOpen && <MoneyDialog title="Monthly pocket money" onClose={() => setPocketOpen(false)}><form onSubmit={submitPocket}><p>Set the amount you receive this month. You can change it anytime.</p><label>Amount<input name="amount" type="number" min="1" step="0.01" defaultValue={totals.income ? totals.income / 100 : ""} autoFocus required /></label><button disabled={pending}>Save pocket money</button></form></MoneyDialog>}
    {incomeOpen && <MoneyDialog title="Add money received" onClose={() => setIncomeOpen(false)}><form onSubmit={submitIncome}><p>Add money you got outside your monthly pocket money—cash, a refund, or help from home.</p><label>Where from?<input name="description" placeholder="e.g. Dad sent money" autoFocus required /></label><label>Amount (₹)<input name="amount" type="number" min="1" step="0.01" placeholder="0" required /></label><button disabled={pending}>Add money</button></form></MoneyDialog>}
    {recurringOpen && <MoneyDialog title="Plan a recurring expense" onClose={() => setRecurringOpen(false)}><form onSubmit={submitRecurring}><p>Use this for costs you expect often. It protects room in your daily spending amount; it does not log a payment until you add it.</p><label>What is it?<input name="description" placeholder="e.g. Rickshaw to college" autoFocus required /></label><label>Amount (₹)<input name="amount" type="number" min="1" step="0.01" placeholder="0" required /></label><label>Category<select name="category" defaultValue=""><option value="">Choose a category</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>How often?<select name="frequency" defaultValue="1"><option value="1">Every day</option><option value="7">Every week</option></select></label><button disabled={pending}>Save recurring plan</button></form></MoneyDialog>}
    {depositOpen && <MoneyDialog title="Add money to savings" onClose={() => setDepositOpen(false)}><form onSubmit={submitDeposit}><p>Record money you&apos;ve actually kept aside. Your required ₹/day will adjust right away.</p><label>Savings plan<select name="plan" defaultValue="">{budgets.filter((budget) => !budget.categoryId && budget.name.startsWith("Save ·")).map((budget) => <option value={budget.id} key={budget.id}>{budget.name.replace("Save · ", "")}</option>)}</select></label><label>Amount (₹)<input name="amount" type="number" min="1" step="0.01" placeholder="0" autoFocus required /></label><button disabled={pending}>Mark as saved</button></form></MoneyDialog>}
    {savingOpen && <MoneyDialog title="Start a savings plan" onClose={() => setSavingOpen(false)}><form onSubmit={submitSaving}><p>Reserve part of this month&apos;s money for something you want.</p><label>Saving for<input name="name" placeholder="e.g. New headphones" autoFocus required /></label><label>Target amount<input name="target" type="number" min="1" step="0.01" placeholder="0" required /></label><button disabled={pending}>Create savings plan</button></form></MoneyDialog>}
  </div>;
}

function MoneyDialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="money-dialog-backdrop" role="presentation" onMouseDown={onClose}><section className="money-dialog" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event) => event.stopPropagation()}><header><CircleDollarSign size={20} /><h2>{title}</h2><button type="button" onClick={onClose}>×</button></header>{children}</section></div>; }
