import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // mobile/ is a separate Expo package with its own toolchain and lint rules;
    // linting it from here applies Next.js rules to React Native code.
    "mobile/**",
    // Generated by `prisma generate`.
    "src/generated/**",
  ]),
]);

export default eslintConfig;
